name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.0
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text

